"""Races and results."""
from __future__ import annotations

import uuid
from datetime import date

from sqlalchemy import Date, Float, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base, TenantMixin


class Race(Base, TenantMixin):
    """A race / championship on the athlete's calendar."""

    __tablename__ = "races"

    name: Mapped[str] = mapped_column(String(255), nullable=False)
    race_date: Mapped[date] = mapped_column(Date, index=True, nullable=False)
    discipline: Mapped[str | None] = mapped_column(String(32), nullable=True)  # XCO/XCM/...
    priority: Mapped[str] = mapped_column(String(8), default="A")  # A (target) / B / C
    location: Mapped[str | None] = mapped_column(String(255), nullable=True)
    distance_km: Mapped[float | None] = mapped_column(Float, nullable=True)
    elevation_gain_m: Mapped[float | None] = mapped_column(Float, nullable=True)
    notes: Mapped[str | None] = mapped_column(Text, nullable=True)


class RaceResult(Base, TenantMixin):
    """The athlete's result and post-race analysis for a race."""

    __tablename__ = "race_results"

    race_id: Mapped[uuid.UUID | None] = mapped_column(
        ForeignKey("races.id"), index=True, nullable=True
    )
    overall_position: Mapped[int | None] = mapped_column(Integer, nullable=True)
    category_position: Mapped[int | None] = mapped_column(Integer, nullable=True)
    finish_time_s: Mapped[int | None] = mapped_column(Integer, nullable=True)
    avg_power: Mapped[float | None] = mapped_column(Float, nullable=True)
    normalized_power: Mapped[float | None] = mapped_column(Float, nullable=True)
    tss: Mapped[float | None] = mapped_column(Float, nullable=True)
    analysis: Mapped[str | None] = mapped_column(Text, nullable=True)  # athlete-written or AI


class RaceAnalysis(Base, TenantMixin):
    """Pre/post-race analysis, written by the athlete or generated by the AI."""

    __tablename__ = "race_analyses"

    race_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("races.id"), index=True, nullable=False
    )
    phase: Mapped[str] = mapped_column(String(8), default="pre")  # pre | post
    author: Mapped[str] = mapped_column(String(16), default="athlete")  # athlete | ai
    content: Mapped[str] = mapped_column(Text, nullable=False)
